### ISSUE TITLE
add API token support

### ISSUE THREAD

**Issue by bbernhard** [bbernhard/imagemonkey-core#102]
Just a short sneak peak how the API token management will probably look like: 

![api_token](https://user-images.githubusercontent.com/5710631/38830468-bb00ff8e-41bc-11e8-9388-eeb8862d93f2.gif)

* tokens can be created and revoked (in case the token got leaked or otherwise compromised)

what's the purpose of the API token(s)/possible features:
* binds the donated photos to a user account (in case the photos were uploaded via script)
* can later be used for credibility (e.q a power user that has already uploaded a lot of pictures without any abusive material, is probably more trustworthy than a new user)
* the user who has uploaded the pictures can already start annotating/labeling them in it's private space, although the picture is not yet unlocked. 
* the uploaded photos can be managed in the user's account (i.e also see how many of your uploaded images are already unlocked)
* it's possible to add arbitrary labels on image upload

**Comment by dobkeratops** [comment]
nice!

**Comment by bbernhard** [comment]
closing this, as it should be done.
