### ISSUE TITLE
polygon tool - close on first point only?

### ISSUE THREAD

**Issue by dobkeratops** [bbernhard/imagemonkey-core#144]
Currently the polygon tool will close the current polygon if you click on *any* vertex..  with more complex or intricate outlines (e.g. needing to draw small or near features ) this can happen accidentally,

I note it highlights the first point in red .. would it be possible to adapt it to only close the polygon when you click back on this first red point?

(I'm guessing this might relate to the code evolving from mixed draw/move to seperate draw/move tools.. e.g. you might have switched it into a move mode if you click on anything;

**Comment by bbernhard** [comment]
already wanted to fix that once, but completely forgot about it again. Many thanks for creating a ticket...I'll have a look :)

**Comment by bbernhard** [comment]
@dobkeratops it should be fixed now. 

a few more changes that were pushed to production today: 

* **moderator rights** you should now have moderator rights. If you click with the right mousebutton on a label you should be able to "remove" it (i.e: you downvote it with a power of 5). see:
![remove_labels](https://user-images.githubusercontent.com/5710631/42423034-7adf49ba-82f3-11e8-9451-b63db6366d76.gif)

* **rework annotations** It should now be possible to rework annotations. see: 
![annotation_rework](https://user-images.githubusercontent.com/5710631/42423052-d33646ea-82f3-11e8-9745-fb1b4fdaa3de.gif)
(at the moment it's pretty slow; I guess those are again the database queries - but I'll have a look at it :))

* **pushed a bunch of labels to production** (#163)

**Comment by dobkeratops** [comment]
seems to work now, awesome, and the new labels unlock a new batch of interesting objects

**Comment by bbernhard** [comment]
should be done
