### ISSUE TITLE
annotation tool: improve closing of polygon

### ISSUE THREAD

**Issue by bbernhard** [bbernhard/imagemonkey-core#223]
proposed by @dobkeratops in #221:
One minor hiccup that might be easy to fix = closing a polygon can be fiddly (e.g. its hard to click the first vertex so you sometimes accidentally add a bunch of vertices around the end). Perhaps the first vertex could be made a bit larger (50%+) and make sure the hit detection with that over-rides other vertices.

**Comment by dobkeratops** [comment]
maybe an even simpler fix for this issue would be a preference for the general point size.. that would achieve the goal of making it easier to close. It might just be that it's a little harder to close on the iPad screen. with a range of settings you could get it right for any device (smaller iPad mini.. larger iPad pro.. cheap capacitive stylus).

**Comment by bbernhard** [comment]
> maybe an even simpler fix for this issue would be a preference for the general point size.. that would achieve the goal of making it easier to close. It might just be that it's a little harder to close on the iPad screen. with a range of settings you could get it right for any device (smaller iPad mini.. larger iPad pro.. cheap capacitive stylus).

like that one, thanks a lot!

I think in a first iteration we could make the point size configureable and store the selected value as a cookie on the client side. I am not sure if its possible to get the device via javascript, but if it is then we could store the point size also server side in a next iteration.

**Comment by dobkeratops** [comment]
what i've seen is you can get the browser name, but thats going to be 'safari' both on MacOSX and iOS.. seems there is a way to get the device (i forget how) but there's going to be a tonne of variations.. and there's a big difference between a pen & raw touchscreen user

**Comment by bbernhard** [comment]
> what i've seen is you can get the browser name, but thats going to be 'safari' both on MacOSX and iOS.. seems there is a way to get the device (i forget how) but there's going to be a tonne of variations.. and there's a big difference between a pen & raw touchscreen user

cool, didn't know that :). The idea would be to start with sane defaults and then let the user do the fine tuning. I am imagening some sort of profile system where users can define individual profiles for their devices (smartphone, tablet, PC, etc.)

**Comment by bbernhard** [comment]
@dobkeratops The next version will contain a new configuration option in the annotation settings which makes it possible to change the vertex size. 

![annotation_settings_vertex_size](https://user-images.githubusercontent.com/5710631/55579307-374aee80-5718-11e9-9a88-29515db5fe88.png)

I hope that makes it easier when used on a tablet :) I'll let you know once it's pushed to production (most probably on the weekends)

**Comment by bbernhard** [comment]
@dobkeratops the changes should now be available on production :)

**Comment by bbernhard** [comment]
should be done
