### ISSUE TITLE
optional sign up

### ISSUE THREAD

**Issue by bbernhard** [bbernhard/imagemonkey-core#65]
an _optional_ sign up functionality could make sense:

* users could see their own contributions (donations, validations, annotations...)
* users could customize their profile (own avatar, prefered default annotation methods, interested labels,..)
* we could show a highscore
...

the sign up should be totally optional; everything should also work without signing up.

**Comment by dobkeratops** [comment]
agree. i guess you can still record the IP and allow disabling contributions from malicious users, and give some seperate weighting factor r.e. the reliability of unveified sources if it's needed

**Comment by bbernhard** [comment]
basic implementation done; the remaining things will be covered in separate tickets
