### ISSUE TITLE
image upload scaling .. maybe 1024

### ISSUE THREAD

**Issue by dobkeratops** [bbernhard/imagemonkey-core#83]
I notice the system rescales the uploads to 1000 pixels, fair enough ( I realise the need to optimise the use of hosted storage space, and high resolution images are an overkill for vision) .. is there any reason to choose 1000 instead of 1024 , which may be a more natural scaling target ( I realise many important images sizes *aren't* powers of 2, like 1920x1080 screens etc.. but if you were to start using the images as texture-maps in some matching tool or whatever, having powers-of-2 would be more natural.)

I guess from years of graphics i just have a learned posative vibe from powers-of-2, and sense of unease about non-powers-of-2... 'if in doubt, choose a power-of-2'

Maybe it doesn't matter as much these days and I'm being irrational/habitual

```
{
  "uuid": "011ebc07-ee0c-4af0-b1db-f0030a242819",
  "provider": "donation",
  "width": 1000,
  "height": 562,
  "annotations": [],
  "validations": [
    {
      "label": "car",
      "num_no": 0,
      "num_yes": 0
    }
  ]
}
```

**Comment by bbernhard** [comment]
Good point - many thanks for bringing that up. 

I'll change it in the sourcecode and push it to production on the weekends (hopefully together with the "trending labels" feature) :)

I think it's also in the Python script I gave you...so you might change it there as well ;)

**Comment by bbernhard** [comment]
production instance should now be updated...closing this now.
